### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/blockchainSecurityDB#1]
1. This image is broken: 
![image](https://user-images.githubusercontent.com/23033765/84576407-8eb80600-ad82-11ea-9e22-a79bb1801735.png)

2. Let's put these into one column called "Max Bounty Payout". Then just show the amount with a hyperlink to the bounty program page. 
![image](https://user-images.githubusercontent.com/23033765/84576509-45b48180-ad83-11ea-8430-7021075f2897.png)

3. The previous should make it possible to double the width of the Audits column

4. On the project pages: move the link to edit the page to the top of the page just below the title, and change the text to: 
"Update this project".

**Comment by dmuhs** [comment]
It would also be interesting to
- sort columns (alphabetically or by max bounty), and
- add a slightly different background to every other row to improve readability

When I tried out the page, the search functionality was broken for me (e.g. typing `0x` didn't yield any results)

**Comment by maurelian** [comment]
> When I tried out the page, the search functionality was broken for me (e.g. typing 0x didn't yield any results)

It seems there's something particular about that string. `0x` has nothing but add a space, and `0x ` starts to turn up results.

Other projects appear without issue as well.

**Comment by kadenzipfel** [comment]
> It would also be interesting to
> 
> * sort columns (alphabetically or by max bounty

By default, the projects are sorted alphabetically. Do we want to create a toggle of some kind to be able to sort based on max bounty?

**Comment by maurelian** [comment]
Yes, that'd be great. 

Do you think there's a simple way we could sort the audits by date of the most recent audit as well?

**Comment by kadenzipfel** [comment]
> Do you think there's a simple way we could sort the audits by date of the most recent audit as well?

Do you mean to keep the projects in the same order and sort the audits per project, or order the projects based on most recent audits? ~~The former would be quite simple whereas the latter would might take a few hours.~~

~~Also, it's worth noting that due to the structure of mkdocs, differently sorted versions of the table would have to be entirely different pages.~~

**Comment by dmuhs** [comment]
Would it be possible to add a drop-in JS lib such as [this](https://github.com/HubSpot/sortable)?

**Comment by kadenzipfel** [comment]
> Would it be possible to add a drop-in JS lib such as [this](https://github.com/HubSpot/sortable)?

Actually, yeah since the md files are just rendered as html this lib works great. I'll get this setup.

**Comment by kadenzipfel** [comment]
All set. You can now sort the table by projects, audit date, and max bounty payout.
