### ISSUE TITLE
Unclear how to reach individual project pages

### ISSUE THREAD

**Issue by kadenzipfel** [ConsenSys/blockchainSecurityDB#2]
I'm somewhat concerned that it's not clear that you can reach an individual project page by clicking on the project name. Although it's mentioned at the top of the page, I'm not sure how many people would notice. Any ideas on how it could be made more clear somehow? Maybe just by modifying the project name links to e.g. '0x Protocol (see more)'?

**Comment by maurelian** [comment]
It's a hyperlink, I think it's pretty clear.

**Comment by kadenzipfel** [comment]
> It's a hyperlink, I think it's pretty clear.

I meant to mention how I imagine it seems like it's a link to the project website, instead of a detailed view of the project.

**Comment by maurelian** [comment]
Yes, but just by mousing over the URL they can see that it goes to another
page on the site:
[image: image.png]

I don't want to add clutter to what is currently a pretty clean site, and
there are bigger fish to fry.
